
# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's:
# README https://bitbucket.org/atlassian/aws-s3-deploy/src/master/README.md
# README https://bitbucket.org/atlassian/aws-cloudfront-invalidate/src/master/README.md

image: node:16

# Workflow Configuration

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            # CI=true in default variables for Bitbucket Pipelines https://support.atlassian.com/bitbucket-cloud/docs/variables-in-pipelines/
            - npm test
            - npm run build
      - step:
          name: Lint the node package
          script:
            # Run your linter of choice here
            - npm install eslint
            - npx eslint src
          caches:
            - node

  custom:
    stop_development:
      - parallel:
        - step:
            trigger: manual
            name: Installing pm2
            script:
              - npm install
        - step: 
            name: Enter on EC2
            script:
              - ssh -i Koneksys.pem ec2-user@54.147.128.163
              - pm2 stop koneksys-interview-development

    start_development:
      - parallel:
        - step:
            trigger: manual
            name: Installing pm2
            script:
              - npm install
        - step: 
            name: Enter on EC2
            script:
              - ssh -i Koneksys.pem ec2-user@54.147.128.163
              - pm2 startOrRestart koneksys-interview-development

    stop_production:
      - parallel:
        - step:
            trigger: manual
            name: Installing pm2
            script:
              - npm install
        - step: 
            name: Enter on EC2
            script:
              - ssh -i Koneksys.pem ec2-user@54.147.128.163
              - pm2 startOrRestart koneksys-interview

    start_production:
      - parallel:
        - step:
            trigger: manual
            name: Installing pm2
            script:
              - npm install
        - step: 
            name: Enter on EC2
            script:
              - ssh -i Koneksys.pem ec2-user@54.147.128.163
              - pm2 start koneksys-interview

  branches:
    development:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              # CI=true in default variables for Bitbucket Pipelines https://support.atlassian.com/bitbucket-cloud/docs/variables-in-pipelines/
              - npm run test
              - npm run build
            artifacts:
              - build/**
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1'
        - step:
            name: deploy development
            script:
              - npm run deploy:development

    main:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              # CI=true in default variables for Bitbucket Pipelines https://support.atlassian.com/bitbucket-cloud/docs/variables-in-pipelines/
              - npm run test
              - npm run build
            artifacts:
              - build/**
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
        - step:
            name: deploy in production
            script:
              - npm run deploy:production
